version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    main: ./cmd/tool-installer
    binary: tooli
    
    ldflags: "-s -w -X main.version={{.Version}} -X main.commitHash={{.Commit}} -X main.commitDate={{.CommitDate}} -X main.builtBy=goreleaser"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{- tolower .ProjectName }}-
      {{- if eq .Arch "amd64" -}}
      x86_64
      {{- else if eq .Arch "386" -}}
      i386
      {{- else -}}
      {{- .Arch -}}
      {{ end }}-
      {{- if eq .Os "windows" -}}
      pc-windows-msvc
      {{- else if eq .Os "linux" -}}
      unknown-linux-gnu
      {{- else -}}
      {{- .Os -}}
      {{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
