// SPDX-License-Identifier: Apache-2.0

package main

var knownTools = map[string]Tool{
	// Shells and common shell command/tool replacements/upgrades
	"bat": {
		Binaries:     []Binary{{Name: "bat", RenameTo: ""}},
		Owner:        "sharkdp",
		Repository:   "bat",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A cat(1) clone with wings.",
	},
	"dua": {
		Binaries:     []Binary{{Name: "dua", RenameTo: ""}},
		Owner:        "Byron",
		Repository:   "dua-cli",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "View disk space usage and delete unwanted data, fast.",
	},
	"dust": {
		Binaries:     []Binary{{Name: "dust", RenameTo: ""}},
		Owner:        "bootandy",
		Repository:   "dust",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A more intuitive version of du in rust",
	},
	"eza": {
		Binaries:     []Binary{{Name: "eza", RenameTo: ""}},
		Owner:        "eza-community",
		Repository:   "eza",
		LinuxAsset:   "eza_x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "eza\\.exe$_x86_64-pc-windows-gnu\\.zip$",
		Description:  "A modern alternative to ls",
	},
	"fd": {
		Binaries:     []Binary{{Name: "fd", RenameTo: ""}},
		Owner:        "sharkdp",
		Repository:   "fd",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A simple, fast and user-friendly alternative to 'find'",
	},
	"fzf": {
		Binaries:     []Binary{{Name: "fzf", RenameTo: ""}},
		Owner:        "junegunn",
		Repository:   "fzf",
		LinuxAsset:   "linux_amd64\\.tar\\.gz$",
		WindowsAsset: "windows_amd64\\.zip$",
		Description:  "A command-line fuzzy finder",
	},
	"numbat": {
		Binaries:     []Binary{{Name: "numbat", RenameTo: ""}},
		Owner:        "sharkdp",
		Repository:   "numbat",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A statically typed programming language for scientific computations with first class support for physical dimensions and units",
	},
	"nushell": {
		Binaries: []Binary{
			{Name: "nu", RenameTo: ""},
			{Name: "nu_plugin_stress_internals", RenameTo: ""},
			{Name: "nu_plugin_query", RenameTo: ""},
			{Name: "nu_plugin_polars", RenameTo: ""},
			{Name: "nu_plugin_inc", RenameTo: ""},
			{Name: "nu_plugin_gstat", RenameTo: ""},
			{Name: "nu_plugin_formats", RenameTo: ""},
			{Name: "nu_plugin_example", RenameTo: ""},
			{Name: "nu_plugin_custom_values", RenameTo: ""},
			{Name: "less", RenameTo: ""},
		},
		Owner:        "nushell",
		Repository:   "nushell",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Data oriented shell",
	},
	"ouch": {
		Binaries:     []Binary{{Name: "ouch", RenameTo: ""}},
		Owner:        "ouch-org",
		Repository:   "ouch",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "(De)compression for your terminal",
	},
	"ripgrep": {
		Binaries:     []Binary{{Name: "rg", RenameTo: ""}},
		Owner:        "burntsushi",
		Repository:   "ripgrep",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Better grep",
	},
	"sd": {
		Binaries:     []Binary{{Name: "sd", RenameTo: ""}},
		Owner:        "chmln",
		Repository:   "sd",
		LinuxAsset:   "x86_64-unknown-linux-gnu",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Better sed",
	},
	"starship": {
		Binaries:     []Binary{{Name: "starship", RenameTo: ""}},
		Owner:        "starship",
		Repository:   "starship",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Cross-shell custom prompt",
	},

	// Linters, formatters, and LSPs
	"biome": {
		Binaries:     []Binary{{Name: "biome", RenameTo: "biome"}},
		Owner:        "biomejs",
		Repository:   "biome",
		LinuxAsset:   "biome-linux-x64-musl",
		WindowsAsset: "biome-win32-x64\\.exe$",
		Description:  "Web Dev formatter and linter",
	},
	"ruff": {
		Binaries:     []Binary{{Name: "ruff", RenameTo: ""}},
		Owner:        "astral-sh",
		Repository:   "ruff",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "An extremely fast Python linter and code formatter",
	},
	"ty": {
		Binaries:     []Binary{{Name: "ty", RenameTo: ""}},
		Owner:        "astral-sh",
		Repository:   "ty",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "An extremely fast Python type checker and language server, written in Rust.",
	},
	"uv": {
		Binaries:     []Binary{{Name: "uv", RenameTo: ""}},
		Owner:        "astral-sh",
		Repository:   "uv",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "An extremely fast Python package installer and resolver, written in Rust.",
	},
	"vale": {
		Binaries:     []Binary{{Name: "vale", RenameTo: ""}},
		Owner:        "errata-ai",
		Repository:   "vale",
		LinuxAsset:   "Linux_64-bit\\.tar\\.gz$",
		WindowsAsset: "Windows_64-bit\\.zip$",
		Description:  "Text linter",
	},

	// Compilers and interpreters
	"bun": {
		Binaries:     []Binary{{Name: "bun", RenameTo: ""}},
		Owner:        "oven-sh",
		Repository:   "bun",
		LinuxAsset:   "linux-x64\\.zip$",
		WindowsAsset: "windows-x64\\.zip$",
		Description:  "Javascript runtime written in Zig",
	},
	"deno": {
		Binaries:     []Binary{{Name: "deno", RenameTo: ""}},
		Owner:        "denoland",
		Repository:   "deno",
		LinuxAsset:   "deno-x86_64-unknown-linux-gnu\\.zip$",
		WindowsAsset: "deno-x86_64-pc-windows-msvc\\.zip$",
		Description:  "A modern runtime for JavaScript and TypeScript",
	},
	"luau": {
		Binaries: []Binary{
			{Name: "luau", RenameTo: ""},
			{Name: "luau-analyze", RenameTo: ""},
			{Name: "luau-compile", RenameTo: ""},
		},
		Owner:        "luau-lang",
		Repository:   "luau",
		LinuxAsset:   "-ubuntu\\.zip$",
		WindowsAsset: "-windows\\.zip$",
		Description:  "A fast, small, safe, gradually typed embeddable scripting language derived from Lua",
	},
	"lune": {
		Binaries:     []Binary{{Name: "lune", RenameTo: ""}},
		Owner:        "lune-org",
		Repository:   "lune",
		LinuxAsset:   "linux-x86_64\\.zip$",
		WindowsAsset: "windows-x86_64\\.zip$",
		Description:  "A standalone Luau runtime ",
	},
	"teal": {
		Binaries:     []Binary{{Name: "tl", RenameTo: ""}},
		Owner:        "teal-language",
		Repository:   "tl",
		LinuxAsset:   "linux-x86_64\\.tar\\.gz$",
		WindowsAsset: "windows-x86_64\\.zip$",
		Description:  "The compiler for Teal, a typed dialect of Lua",
	},

	// Build tools and command runners
	"just": {
		Binaries:     []Binary{{Name: "just", RenameTo: ""}},
		Owner:        "casey",
		Repository:   "just",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Just a command runner",
	},
	"ninja": {
		Binaries:     []Binary{{Name: "ninja", RenameTo: ""}},
		Owner:        "ninja-build",
		Repository:   "ninja",
		LinuxAsset:   "ninja-linux\\.zip$",
		WindowsAsset: "ninja-win\\.zip$",
		Description:  "A small build system with a focus on speed",
	},

	// Text processors and static site generators
	"hugo": {
		Binaries:     []Binary{{Name: "hugo", RenameTo: ""}},
		Owner:        "gohugoio",
		Repository:   "hugo",
		LinuxAsset:   "hugo_extended_[\\d\\.]+_linux-amd64\\.tar\\.gz$",
		WindowsAsset: "hugo_extended_[\\d\\.]+_windows-amd64\\.zip$",
		Description:  "Single binary static site generator",
	},
	"mdbook": {
		Binaries:     []Binary{{Name: "mdbook", RenameTo: ""}},
		Owner:        "rust-lang",
		Repository:   "mdBook",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Create a book from markdown files",
	},
	"mdbook-admonish": {
		Binaries:     []Binary{{Name: "mdbook-admonish", RenameTo: ""}},
		Owner:        "tommilligan",
		Repository:   "mdbook-admonish",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A preprocessor for mdbook to add Material Design admonishments",
	},
	"pandoc": {
		Binaries:     []Binary{{Name: "pandoc", RenameTo: ""}},
		Owner:        "jgm",
		Repository:   "pandoc",
		LinuxAsset:   "linux-amd64\\.tar\\.gz$",
		WindowsAsset: "windows-x86_64\\.zip$",
		Description:  "Universal markup converter",
	},
	"typst": {
		Binaries:     []Binary{{Name: "typst", RenameTo: ""}},
		Owner:        "typst",
		Repository:   "typst",
		LinuxAsset:   "x86_64-unknown-linux-gnu.tar.xz",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A new markup-based typesetting system",
	},
	"zola": {
		Binaries:     []Binary{{Name: "zola", RenameTo: ""}},
		Owner:        "getzola",
		Repository:   "zola",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "Fast single binary static site generator",
	},

	// Git/VCS
	"delta": {
		Binaries:     []Binary{{Name: "delta", RenameTo: ""}},
		Owner:        "dandavison",
		Repository:   "delta",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A syntax-highlighting pager for git, diff, grep, and blame output",
	},
	"github": {
		Binaries:     []Binary{{Name: "gh", RenameTo: ""}},
		Owner:        "cli",
		Repository:   "cli",
		LinuxAsset:   "linux amd64$",
		WindowsAsset: "windows amd64$",
		Description:  "GitHub's official command line tool",
	},
	"gitui": {
		Binaries:     []Binary{{Name: "gitui", RenameTo: ""}},
		Owner:        "extrawurst",
		Repository:   "gitui",
		LinuxAsset:   "gitui-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "gitui-win\\.tar\\.gz$",
		Description:  "Blazing fast terminal-ui for git written in rust",
	},
	"jujutsu": {
		Binaries:     []Binary{{Name: "jj", RenameTo: ""}},
		Owner:        "martinvonz",
		Repository:   "jj",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A Git-compatible VCS that is both simple and powerful",
	},
	"lazygit": {
		Binaries:     []Binary{{Name: "lg", RenameTo: ""}},
		Owner:        "jesseduffield",
		Repository:   "lazygit",
		LinuxAsset:   "Linux_x86_64\\.tar\\.gz$",
		WindowsAsset: "Windows_x86_64\\.zip$",
		Description:  "Simple terminal UI for git commands",
	},

	// Text editors
	"micro": {
		Binaries:     []Binary{{Name: "micro", RenameTo: ""}},
		Owner:        "zyedidia",
		Repository:   "micro",
		LinuxAsset:   "linux64\\.tar\\.gz$",
		WindowsAsset: "win64\\.zip$",
		Description:  "A modern and intuitive terminal-based text editor",
	},

	// Multimedia
	"freeze": {
		Binaries:     []Binary{{Name: "freeze", RenameTo: ""}},
		Owner:        "charmbracelet",
		Repository:   "freeze",
		LinuxAsset:   "Linux_x86_64\\.tar\\.gz$",
		WindowsAsset: "Windows_x86_64\\.zip$",
		Description:  "Generate images of code and terminal output",
	},
	"vhs": {
		Binaries:     []Binary{{Name: "vhs", RenameTo: ""}},
		Owner:        "charmbracelet",
		Repository:   "vhs",
		LinuxAsset:   "Linux_x86_64\\.tar\\.gz$",
		WindowsAsset: "Windows_x86_64\\.zip$",
		Description:  "Your CLI home video recorder",
	},
	"yt-dlp": {
		Binaries:     []Binary{{Name: "yt-dlp", RenameTo: ""}},
		Owner:        "yt-dlp",
		Repository:   "yt-dlp",
		LinuxAsset:   "yt-dlp_linux$",
		WindowsAsset: "yt-dlp\\.exe$",
		Description:  "A feature-rich command-line audio/video downloader",
	},

	// Cryptography
	"age": {
		Binaries: []Binary{
			{Name: "age", RenameTo: ""},
			{Name: "age-keygen", RenameTo: ""},
		},
		Owner:        "FiloSottile",
		Repository:   "age",
		LinuxAsset:   "linux-amd64\\.tar\\.gz$",
		WindowsAsset: "windows-amd64\\.zip$",
		Description:  "A simple, modern and secure encryption tool (and Go library) with small explicit keys, no config options, and UNIX-style composability.",
	},
	"minisign": {
		Binaries:     []Binary{{Name: "minisign", RenameTo: ""}},
		Owner:        "jedisct1",
		Repository:   "minisign",
		LinuxAsset:   "linux\\.tar\\.gz$",
		WindowsAsset: "win64\\.zip$",
		Description:  "A dead simple tool to sign files and verify digital signatures.",
	},
	"mkcert": {
		Binaries:     []Binary{{Name: "mkcert", RenameTo: ""}},
		Owner:        "FiloSottile",
		Repository:   "mkcert",
		LinuxAsset:   "linux-amd64",
		WindowsAsset: "windows-arm64\\.exe$",
		Description:  "A simple zero-config tool to make locally trusted development certificates with any names you'd like.",
	},

	// AI
	"codex": {
		Binaries: []Binary{
			{Name: "codex-x86_64-pc-windows-msvc", RenameTo: "codex"},
			{Name: "codex-x86_64-unknown-linux-gnu", RenameTo: "codex"},
		},
		Owner:        "openai",
		Repository:   "codex",
		LinuxAsset:   "codex-x86_64-unknown-linux-gnu.tar\\.gz$",
		WindowsAsset: "codex-x86_64-pc-windows-msvc\\.exe$\\.zip$",
		Description:  "Lightweight coding agent that runs in your terminal",
	},
	"crush": {
		Binaries:     []Binary{{Name: "crush", RenameTo: ""}},
		Owner:        "charmbracelet",
		Repository:   "crush",
		LinuxAsset:   "Linux_x86_64\\.tar\\.gz$",
		WindowsAsset: "Windows_x86_64\\.zip$",
		Description:  "The glamourous AI coding agent for your favourite terminal",
	},
	"opencode": {
		Binaries:     []Binary{{Name: "opencode", RenameTo: ""}},
		Owner:        "sst",
		Repository:   "opencode",
		LinuxAsset:   "linux-x64\\.tar\\.gz$",
		WindowsAsset: "windows-x64\\.zip$",
		Description:  "The open source coding agent.",
	},

	// Miscellaneous
	"hledger": {
		Binaries: []Binary{
			{Name: "hledger", RenameTo: ""},
			{Name: "hledger-ui", RenameTo: ""},
			{Name: "hledger-web", RenameTo: ""},
		},
		Owner:        "simonmichael",
		Repository:   "hledger",
		LinuxAsset:   "linux-x64\\.zip$",
		WindowsAsset: "windows-x64\\.zip$",
		Description:  "Robust, fast, intuitive plain text accounting tool with CLI, TUI and web interfaces.",
	},
	"hyperfine": {
		Binaries:     []Binary{{Name: "hyperfine", RenameTo: ""}},
		Owner:        "sharkdp",
		Repository:   "hyperfine",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.zip$",
		Description:  "A command-line benchmarking tool",
	},
	"miniserve": {
		Binaries:     []Binary{{Name: "miniserve", RenameTo: ""}},
		Owner:        "svenstaro",
		Repository:   "miniserve",
		LinuxAsset:   "x86_64-unknown-linux-gnu",
		WindowsAsset: "x86_64-pc-windows-msvc\\.exe$",
		Description:  "For when you really just want to serve some files over HTTP right now!",
	},
	"tealdeer": {
		Binaries:     []Binary{{Name: "tealdeer", RenameTo: "tldr"}},
		Owner:        "dbrgn",
		Repository:   "tealdeer",
		LinuxAsset:   "tealdeer-linux-x86_64-musl",
		WindowsAsset: "windows-x86_64-msvc\\.exe$",
		Description:  "A very fast implementation of tldr in Rust.",
	},
	"tokei": {
		Binaries:     []Binary{{Name: "tokei", RenameTo: ""}},
		Owner:        "XAMPPRocky",
		Repository:   "tokei",
		LinuxAsset:   "x86_64-unknown-linux-gnu\\.tar\\.gz$",
		WindowsAsset: "x86_64-pc-windows-msvc\\.exe$",
		Description:  "Count your code, quickly.",
	},
	"tailwind": {
		Binaries:     []Binary{{Name: "tailwind", RenameTo: ""}},
		Owner:        "tailwindlabs",
		Repository:   "tailwindcss",
		LinuxAsset:   "tailwindcss-linux-x64$",
		WindowsAsset: "tailwindcss-windows-x64\\.exe$",
		Description:  "Tailwind CSS standalone CLI tool",
	},
}
